language: go

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=amd64
    
script: go test -test.coverprofile= github.com/sanbit/cmap

go:
  - 1.3
  - 1.6